# Generated by Django 5.2.9 on 2026-01-03 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecycleBinItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('PROJECT', '项目')], max_length=32)),
                ('object_id', models.BigIntegerField(blank=True, null=True)),
                ('object_code', models.CharField(blank=True, max_length=64)),
                ('object_name', models.CharField(blank=True, max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('is_restored', models.BooleanField(default=False)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_items', to=settings.AUTH_USER_MODEL)),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
