# Generated by Django 5.2.9 on 2026-01-05 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fileacl'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileentry',
            name='version_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('size_bytes', models.BigIntegerField()),
                ('mime_type', models.CharField(blank=True, max_length=128)),
                ('storage_key', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_file_versions', to=settings.AUTH_USER_MODEL)),
                ('file_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.fileentry')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('file_entry', 'version_number')},
            },
        ),
    ]
