# Generated by Django 5.2.9 on 2026-01-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fileentry_version_number_fileversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileentry',
            name='search_text',
            field=models.TextField(blank=True),
        ),
    ]
